### ISSUE TITLE
Simple text cards

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-muc-web-22-1#1]
## Value Proposition
**As a** User
**I need** to write down text cards
**to be able to** talk about them in a group

## Description
![text-cards](https://user-images.githubusercontent.com/157286/159287506-aaee18ce-6b3a-429e-80d9-b51184f7095a.png)

## Acceptance Criteria

- [ ] Empty input or only whitespace does not submit
- [ ] Text has a max length of 200 characters
- [ ] New card shows up on last position
- [ ] Text wraps in card (no ellipsis)
- [ ] LATER USER STORY: New card scrolls into view if neccessary

## Tasks
- [ ] Create branch `simple-text-cards`
- [ ] Create Entry component with Storybook and specs
- [ ] Create EntryForm component with Storybook and specs
- [ ] Add Entry and EntryForm to App
- [ ] Update styles
- [ ] Test on mobile device / different browser
