### ISSUE TITLE
add-author

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-muc-web-22-1#2]
## Value Proposition

**As a** User
**I need** to add an author to each card
**to be able to** identify whose idea is on the card

## Description
![add-author](https://user-images.githubusercontent.com/157286/159448022-7b123c53-051f-4398-b53a-eb9c5aa434ec.png)

## Acceptance Criteria

- [ ] If author is empty, use "Anonymous"
- [ ] "Contribution" has a max length of 200
- [ ] "Contribution" is resetted after submit
- [ ] If "Contribution" is empty (or has only whitespace), don't send
- [ ] "Author" has a max length of 50
- [ ] All whitespaces in inputs are trimmed on submit
- [ ] On submit, a new card is created on whiteboard

## Tasks

- [ ] Create feature branch `add-author`
- [ ] Create Button component w/ storybook and specs
- [ ] Update EntryForm component
- [ ] Update EntryForm specs
- [ ] Update Entry card: add author, update styles
- [ ] Update App
- [ ] Test in other browser
