### ISSUE TITLE
Mark as done

### ISSUE THREAD

**Issue by badabam** [badabam/lean-coffee-board-muc-web-22-1#3]
## Value Proposition

**As a** user
**I need** to mark the cards as done
**to be able to** tell apart open cards from done cards

## Description

![mark-as-done](https://user-images.githubusercontent.com/157286/159467972-61c87eeb-3fe0-4b35-8418-eec2940195c0.png)

## Acceptance Criteria

- [ ] Checkbox toggles on click
- [ ] Checked cards move to the end
- [ ] Unchecking a card moves it to last position of all unchecked cards
- [ ] Marking a card is persisted in the database
- [ ] Everybody can mark every card as done

## Tasks

- [x] Create branch `mark-as-done`
- [x] Add checkbox to Entry card and update specs
- [x] Add toggle logic to checkbox and update specs
- [ ] Add sort logic and add specs
- [ ] Update backend logic (Entry model, route)
- [ ] Check in other browser
